### ISSUE TITLE
On downloading pdf files

### ISSUE THREAD

**Issue by FraMecca** [mehdikhrichfa/noc-test-scraping#2]
Consider adding two options specified by command line:

* download-path: used to specify in which directory pdf files must be saved
* print-only: modifies the behaviour of the program in order not to download the pdf files

**Comment by mehdikhrichfa** [comment]
Added two options
```
-s FILES_STORE="/path/to/valid/dir"        #download to selected folder
-a print_only=true                         #print without downloading
```
